default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['MIP_V3_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: mip_v3_development

test:
  <<: *default
  database: mip_v3_test

production:
  <<: *default
  database: mip_v3_production
