default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['MIP_V3_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: mip_v3_development
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

custom_development:
  <<: *default
  database: mip_v3_custom_development
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: mip_v3_test
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: mip_v3_production
