:queues:
  - critical
  - default
  - low

:scheduler:
  :schedule:
    import_tasks:
      cron: "*/15 6-18 * * *"
      class: "ImportTasksScheduler"
      queue: low
    add_vacation_days:
      cron: "0 0 1 * *"
      class: "AddVacationDaysScheduler"
      queue: default
    check_assignee_on_vacation:
      cron: "0 9 6-18 * *"
      class: "CheckAssigneeOnVacationScheduler"
      queue: default
    db_task_cleaner:
      cron: "5 */1 6-18 * *"
      class: "DbTaskCleanerScheduler"
      queue: critical
