:scheduler:
  :schedule:
    import_tasks:
      cron: '*/30 * * * *'
      class: 'ImportTasksScheduler'
      queue: default
    add_vacation_days:
      cron: '0 0 1 * *'
      class: 'AddVacationDaysScheduler'
      queue: default
